### PR TITLE
Add Carting Framework

### PR DESCRIPTION
**Pull request by artemnovichkov**

### CODE REVIEW

**Comment by artemnovichkov** [comment]
Hi, @JohnSundell! Have you watched this PR?..

**Comment by JohnSundell** [comment]
@artemnovichkov Thanks for this suggestion! Correct me if I'm wrong, but it seems like Carting isn't a framework to be used in Swift scripts, but rather a script itself. In that case it should go under the "Examples" section instead of under "Frameworks".

**Comment by artemnovichkov** [comment]
@JohnSundell, done!

**Comment by JohnSundell** [comment]
Awesome, thanks 👍

**Pull request merged**
